name = "clientflow-api"
main = "src/index.ts"
compatibility_date = "2026-09-27"

[vars]
APP_NAME = "ClientFlow"
ENVIRONMENT = "development"

[[d1_databases]]
binding = "DB"
database_name = "clientflow-db"
database_id = "26beb5c1-8e5f-4e4c-a724-a71299573e98"

[[r2_buckets]]
binding = "FILES"
bucket_name = "clientflow-files"
